[project]
name = "promptpy"
version = "0.1.0"
description = "A Python command line input and validation library"
readme = "README.md"
authors = [
    { name = "Neil Martin", email = "neil@fourtrees.tech" }
]
requires-python = ">=3.9"
dependencies = []

[tool.mypy]
packages = ["src.promptpy"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
